# Cloud Build configuration for automated deployment
# This file is used when you connect Cloud Build to your GitHub repository

steps:
    # Step 1: Build the Docker image
    - name: 'gcr.io/cloud-builders/docker'
      args:
          - 'build'
          - '-t'
          - 'gcr.io/$PROJECT_ID/perps-vibe-ai:$COMMIT_SHA'
          - '-t'
          - 'gcr.io/$PROJECT_ID/perps-vibe-ai:latest'
          - '.'

    # Step 2: Push the Docker image to Container Registry
    - name: 'gcr.io/cloud-builders/docker'
      args:
          - 'push'
          - 'gcr.io/$PROJECT_ID/perps-vibe-ai:$COMMIT_SHA'

    # Step 3: Push latest tag
    - name: 'gcr.io/cloud-builders/docker'
      args:
          - 'push'
          - 'gcr.io/$PROJECT_ID/perps-vibe-ai:latest'

    # Step 4: Deploy to Cloud Run
    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      entrypoint: gcloud
      args:
          - 'run'
          - 'deploy'
          - 'perps-vibe-ai'
          - '--image=gcr.io/$PROJECT_ID/perps-vibe-ai:$COMMIT_SHA'
          - '--region=asia-southeast1'
          - '--platform=managed'
          - '--port=8080'
          - '--allow-unauthenticated'
          - '--min-instances=1'
          - '--max-instances=1'
          - '--memory=512Mi'
          - '--cpu=1'
          - '--timeout=300'
          - '--set-env-vars=NODE_ENV=production,LOG_LEVEL=info'
          - '--set-secrets=ASTER_API_KEY=aster-api-key:latest,ASTER_API_SECRET=aster-api-secret:latest,ASTER_PRIVATE_KEY=aster-private-key:latest,API_KEY_ACCESS=api-key-access:latest'

# Images to be pushed to Container Registry
images:
    - 'gcr.io/$PROJECT_ID/perps-vibe-ai:$COMMIT_SHA'
    - 'gcr.io/$PROJECT_ID/perps-vibe-ai:latest'

# Build timeout
timeout: '1200s'

# Build options
options:
    machineType: 'N1_HIGHCPU_8'
    logging: CLOUD_LOGGING_ONLY
